// ColumnTooltips.js

const columnTooltips = [
  'Tooltip for col1',
  'Tooltip for col2',
  'Tooltip for col3',
  'Tooltip for col4',
  'Tooltip for col5',
  'Tooltip for col6',
  'Tooltip for col7',
  'Tooltip for col8',
  'Tooltip for col9',
  'Tooltip for col10',
  'Tooltip for col11',
  'Tooltip for col12',
  'Tooltip for col13',
  'Tooltip for col14',
  'Tooltip for col15',
  'Tooltip for col16',
  'Tooltip for col17',
  'Tooltip for col18',
  'Tooltip for col19',
  'Tooltip for col20',
  'Tooltip for col21',
  'Tooltip for col22',
  'Tooltip for col23',
  'Tooltip for col24',
  'Tooltip for col25',
  'Tooltip for col26',
  'Tooltip for col27',
  'Tooltip for col28',
  'Tooltip for col29',
  'Tooltip for col30',
];

export default columnTooltips;
