const faqAnswers = {
  'data-included1': 'VirJenDB is the comprehensive virus database developed in Jena, Germany covering all viruses. It is a web portal to access publicly available virus sequences and metadata and offers search, browse, visualization, summary and analysis services.',
  'data-included': 'Publicly available virus metadata and sequences. See more at our <a href="DataSources" style= color: #0000ff; font-weight: bold;">Data Sources</a> page.',
  'search-specific-info': 'Enter the virus name, abbreviation or host into the <a href="/">search field on the home page</a>, or click on one of the suggested searches. One can also use additional keywords in the <a href="AdvancedSearch">advanced search</a>, as well as browse through the<a href="Browse"> taxonomy.</a>',
  'contribute-data': 'The best way to submit virus sequencing data to VirJenDB is indirectly via submission to one of the INSDC repositories: NCBI GenBank<a href="https://www.ncbi.nlm.nih.gov/labs/virus/vssi/docs/submit/">(submission help)</a>, ENA or the DDBJ. VirJenDB uses these repositories as a source of data',
  'download-export-data': 'Yes, you can download metadata and sequences as text and FASTA files on the <a href="Downloads"> Downloads page.</a>',
  // 'virus-vs-bacteria': '2222222',
  // 'common-symptoms': 'Common symptoms of viral infections include fever, fatigue, body aches, sore throat, cough, runny nose, and headache. Some viruses can also cause skin rashes or conjunctivitis (pink eye).',
  // 'viral-infections-diagnosis': 'Viral infections are diagnosed through a combination of medical history, physical examination, and laboratory tests. For example, a blood test can detect the presence of antibodies against the virus, or a nasal or throat swab can be used to detect the virus itself.',
  // 'antiviral-treatments': 'There are several antiviral drugs available for the treatment of viral infections, including acyclovir for herpes simplex virus, oseltamivir for influenza, and ribavirin for hepatitis C. Some viruses, such as HIV, require a combination of antiviral drugs to effectively manage the infection.',
  // 'role-of-vaccines': 'Vaccines help to prevent viral infections by introducing a weakened or inactivated form of the virus into the body, which triggers the immune system to produce antibodies against the virus. If the individual is later exposed to the live virus, their immune system will recognize and attack it, preventing the development of the disease.',
  // 'virologists-study': 'Virologists study the evolution and spread of viruses by analyzing viral genomes and tracking the genetic changes that occur over time. They also study how viruses interact with host cells and the environments in which they spread, such as through close contact between individuals or through contaminated surfaces or water sources.',
  // 'virus-genetic-information': 'The genetic information of a virus is stored in its RNA or DNA genome. When a virus infects a host cell, it hijacks the cell\'s machinery to replicate its genome and produce new virus particles.',
  // 'common-viruses-in-humans': 'The most common viruses that affect humans include the common cold, influenza, human papillomavirus (HPV), and the herpes virus.',
  // 'role-of-international-health-organizations': 'The role of international health organizations in controlling the spread of viruses is crucial in ensuring global health security. These organizations coordinate and collaborate with governments, health care providers, and other stakeholders to monitor the spread of viruses, develop and implement evidence-based strategies to prevent their transmission, and respond to outbreaks when they occur. They also play a key role in promoting international cooperation and coordination in the development of treatments, vaccines, and other medical interventions. Additionally, they provide technical assistance and guidance to countries on surveillance, laboratory testing, and outbreak response. The goal is to ensure that all countries have the capacity to detect and respond to viral threats, and to prevent the spread of viruses from one country to another.',
};

export default faqAnswers;
